### ISSUE TITLE
x86-installer gives "Internal error: Cannot expand 'commonpf64' constant ...."

### ISSUE THREAD

**Issue by ionum** [maphew/svg-explorer-extension#63]
Installing the x86-installer on win10-32bit gives the following error-msg:

Internal error: Cannont expand "commonpf64" constant on this version of windows.

I suppose, that changing a x64 variable has been forgotten on the x86-installer....

**Comment by tibold** [comment]
I have no 32 bit machines anymore and couldn't test this scenario, but seems I didn't get this right.
I'll have it fixed soon.

**Comment by tibold** [comment]
It seems this has been fixed in  da2df917e95edd3a666bd13bba30d718cb74750a

Could you please test the installer from the latest development build:
https://ci.appveyor.com/project/tibold/svg-explorer-extension/builds/30516120/artifacts

**Comment by Premium4Free** [comment]
![Anotación 2020-03-22 002831](https://user-images.githubusercontent.com/39070725/77241684-89f51300-6bd4-11ea-92b8-cd2713e7b065.jpg)

I still can't install it.

**Comment by ghost** [comment]
![Anotación 2020-03-22 002831](https://user-images.githubusercontent.com/39070725/77242131-f9b9cc80-6bd9-11ea-8122-05f2266cc4a9.jpg)

I still can't install it.

**Comment by burakt91** [comment]
Windows 7 x86 here. I can install it successfully from your link, but i get the same error when i install it from this repository's releases section.

**Comment by maphew** [comment]
Many of the recent bug reports stem from people using the Releases instead of the [automatic builds](https://github.com/tibold/svg-explorer-extension#automatic-builds). Is there some way to turn the releases off until a valid one can be published? ... or maybe just edit the release note comment to say they're here for historical reasons and most people will be happier with a green auto build.

**Comment by gabi2367** [comment]
It works now! Thank you!
